# Generated by Django 5.1.7 on 2025-04-07 19:24

from django.db import migrations


def create_demo_user(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Settings = apps.get_model('user', 'Settings')

    if not User.objects.filter(username='demo').exists():
        user = User.objects.create_user(
            username='demo',
            email='demo@shaheen.com',
            password='12345678',
            first_name='Demo',
            last_name='User'
        )
        Settings.objects.create(user=user)

class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_demo_user),
    ]
