# Generated by Django 5.1.7 on 2025-03-19 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_days', to='trips.trip')),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('off', 'Off Duty'), ('sb', 'Sleeper Berth'), ('driving', 'Driving'), ('on', 'On Duty Not Driving')], max_length=10)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('log_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='driver_logs.logday')),
            ],
        ),
    ]
